package co.astrnt.qasdk.constants

object PreferenceKey {
    const val KEY_FIRST_OPEN = "key_first_open"
    const val KEY_SHOW_RATING = "key_show_rating"
    const val KEY_NEED_REGISTER = "key_need_register"
    const val KEY_UPLOAD_ID = "UploadId"
    const val KEY_DOWNLOAD_ID = "DownloadId"
    const val KEY_WATCH_WELCOME_VIDEO = "isFinishWatchWelcomeVideo"
    const val KEY_WELCOME_VIDEO = "WelcomeVideoDao"
    const val KEY_WELCOME_VIDEO_URI = "WelcomeVideoUri"
    const val KEY_GDPR = "GdprDao"
    const val KEY_CONTINUE = "ContinueInterview"
    const val KEY_SHOW_UPLOAD = "ShowUpload"
    const val KEY_FINISH_SESSION = "finishSession"
    const val KEY_START_SESSION = "startSession"
    const val KEY_FINISH_QUESTION = "finishQuestionFinish"
    const val KEY_FINISH_INTERVIEW = "FinishInterview"
    const val KEY_IS_SOURCING = "IsSourcing"
    const val KEY_UNAUTHORIZED = "IsUnauthorized"
    const val KEY_IS_PROFILE = "IsProfile"
    const val KEY_INTERVIEW_CODE = "InterviewCode"
    const val KEY_TOKEN = "Token"
    const val KEY_JOB_ID = "JobId"
    const val KEY_CANDIDATE_ID = "CandidateId"
    const val KEY_COMPANY_ID = "CompanyId"
    const val KEY_LAST_LOG_INDEX = "LastLogIndex"
    const val KEY_LAST_TIMER = "LastTimer"
    const val KEY_SELF_PACE = "SelfPace"
    const val KEY_PRACTICE_RETAKE = "PracticeRetake"
    const val KEY_LAST_API_CALL = "LastApiCall"
    const val KEY_CV_START_CALLED = "CvStart"
    const val KEY_IS_RUNNING_UPLOADING = "RunningUploading"
    const val KEY_IS_RUNNING_COMPRESSING = "RunningCOMPRESSING"
    const val KEY_IS_LAST_QUESTION = "LastQuestion"
    const val KEY_IS_SECTION_SUMMARY = "SECTIONSUMMARY"
}
